### ISSUE TITLE
import module error

### ISSUE THREAD

**Issue by arslantoor** [HamidMoghaddam/Lex#1]
import boto3
error details write bellow.

PS C:\Users\zeeto\OneDrive\Documents\python lamba function chat bot\Lex-master> & C:/Users/zeeto/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py"
  File "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py", line 1, in <module>      
    import boto3
ModuleNotFoundError: No module named 'boto3'
PS C:\Users\zeeto\OneDrive\Documents\python lamba function chat bot\Lex-master> & C:/Users/zeeto/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py"
  File "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py", line 1, in <module>      
    import boto3
ModuleNotFoundError: No module named 'boto3'
PS C:\Users\zeeto\OneDrive\Documents\python lamba function chat bot\Lex-master> & C:/Users/zeeto/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py"
Traceback (most recent call last):
  File "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py", line 1, in <module>      
    import boto3
ModuleNotFoundError: No module named 'boto3'
PS C:\Users\zeeto\OneDrive\Documents\python lamba function chat bot\Lex-master> & C:/Users/zeeto/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py"
Traceback (most recent call last):
  File "c:/Users/zeeto/OneDrive/Documents/python lamba function chat bot/Lex-master/lambda_function.py", line 1, in <module>      
    import boto3
ModuleNotFoundError: No module named 'boto3'

**Comment by HamidMoghaddam** [comment]
You need to use [AWS Lambda](https://aws.amazon.com/lambda/) to run the code.
